image: Visual Studio 2019
configuration: Release

install:
    - git submodule update --init
    - appveyor DownloadFile http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe -FileName yasm.exe
    - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%
    - cmake . -G "Visual Studio 16 2019" -A x64 -DCMAKE_ASM_NASM_COMPILER="yasm.exe"

build:
  project: svt-av1.sln

artifacts:
    - path: bin\Release\SvtAv1*.exe
      name: $(APPVEYOR_PROJECT_NAME)
    - path: bin\Release\SvtAv1*.dll
      name: $(APPVEYOR_PROJECT_NAME)

deploy:
  - provider: GitHub
    artifact: $(APPVEYOR_PROJECT_NAME)
    auth_token:
      secure: 'sf0pQXlPI+X6LoAR8QUJB74jjzNxcLGOXI3H0nbxJq8llvGPG/TAUd87hq5iHZXo'
    prerelease: true
    on:
      appveyor_repo_tag: true
