name: Patches
on:
  push:
    paths-ignore:
      - "Docs/*"
      - .travis.yml
      - appveyor.yml
      - .gitignore
      - "*.md"
  pull_request:
    paths-ignore:
      - "Docs/*"
      - .travis.yml
      - appveyor.yml
      - .gitignore
      - "*.md"

jobs:
  ffmpeg-patch:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            CC: gcc
            CXX: g++
          - os: macos-10.15
            CC: clang
            CXX: clang++
    runs-on: ${{ matrix.os }}
    env:
      CC: ccache ${{ matrix.CC }}
      CXX: ccache ${{ matrix.CXX }}
      # Seems macOS made it so you can't do anything in /usr except /usr/local even with root permissions
      LD_LIBRARY_PATH: /usr/local/lib
      PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
    steps:
      - name: Clone FFmpeg
        uses: actions/checkout@v2
        with:
          repository: FFmpeg/FFmpeg

      - name: Cache ccache files
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ffmpeg-${{ hashFiles('**/*.c') }}
          restore-keys: ${{ runner.os }}-ffmpeg-

      - name: Install dependencies (ubuntu)
        if: matrix.os == 'ubuntu-18.04'
        run: |
          sudo apt-get update &&
          sudo apt-get install -y yasm nasm cmake ccache ninja-build
      - name: Install dependencies (mac)
        if: matrix.os == 'macos-10.15'
        run: |
          brew update
          brew install yasm nasm ccache pkg-config ninja
      - name: Check dependencies
        run: |
          [ -d ~/.ccache ] && sudo chown -R "$USER": ~/.ccache
          echo "::set-env name=CCACHE_DIR::$HOME/.ccache"
          $CC --version
          yasm --version
          cmake --version
          ccache --version

      - name: Clone SVT-AV1
        uses: actions/checkout@v2
        with:
          path: svtav1
      - name: Configure SVT-AV1
        run: |
          sudo -E cmake -S svtav1 -B svtav1-build -GNinja  -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_APPS=OFF -DBUILD_DEC=OFF
          sudo -E cmake --build svtav1-build --parallel 4 --target install

      - name: Clone libaom
        run: git clone https://aomedia.googlesource.com/aom
      - name: Configure libaom
        run: |
          sudo -E cmake -S aom -B aom-build -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DENABLE_TESTS=0 -DENABLE_EXAMPLES=0 -DENABLE_DOCS=0 -DENABLE_TESTDATA=0 -DENABLE_TOOLS=0
          sudo -E cmake --build aom-build --target install

      - name: Clone libvpx
        run: git clone https://chromium.googlesource.com/webm/libvpx
      - name: Configure libvpx
        run: |
          mkdir -p vpx-build && cd vpx-build || exit 1
          sudo -E ../libvpx/configure --disable-{examples,webm-io,libyuv,postproc,shared,unit-tests,docs,install-bins} --enable-{vp9-postproc,vp9-highbitdepth}
          sudo -E make -j $(getconf _NPROCESSORS_ONLN 2>/dev/null || sysctl -n hw.ncpu) install

      - name: Configure FFmpeg
        run: |
          [ -d ~/.ccache ] && sudo chown -R "$USER": ~/.ccache
          ./configure --arch=x86_64 --pkg-config-flags="--static" --cc="${CC:-ccache gcc}" --cxx="${CXX:-ccache g++}" --enable-{gpl,static} --enable-lib{vpx,aom,svtav1} --disable-shared || {
            less ffbuild/config.log
            exit 1
          }
      - name: Build FFmpeg
        run: sudo -E make --quiet -j "$(getconf _NPROCESSORS_ONLN 2>/dev/null || sysctl -n hw.ncpu)" install

      - name: Download videos
        run: |
          for url in raw.githubusercontent.com/OpenVisualCloud/SVT-AV1-Resources/master randomderp.com; do
            curl -LO https://$url/video.tar.gz && break
          done
          tar xf video.tar.gz
      - name: Run ffmpeg
        run: ffmpeg -i akiyo_cif.y4m -c:v libsvtav1 akiyo.webm

  gstreamer-patch:
    runs-on: ubuntu-18.04
    env:
      CC: ccache gcc
      CXX: ccache g++
    steps:
      - uses: actions/checkout@v2
      - name: Cache ccache files
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-gstreamer-${{ hashFiles('**/*.c') }}
          restore-keys: ${{ runner.os }}-gstreamer-
      - name: Install dependencies
        run: |
          [ -d ~/.ccache ] && sudo chown -R "$USER": ~/.ccache
          sudo apt-get update
          sudo apt-get install -y yasm cmake ccache \
            libgstreamer{,-plugins-base}1.0-dev \
            gstreamer1.0-{tools,plugins-{good,bad}} \
            pkg-config \
            ninja-build \
            python3{,-{pip,setuptools,wheel}}
          pip3 install --user meson
          printf '%s\n' "::set-env name=CCACHE_DIR::$HOME/.ccache" \
            "::set-env name=PATH::$PATH:$HOME/.local/bin"
      - name: Configure SVT-AV1
        run: cmake -S "$GITHUB_WORKSPACE" -B Build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/usr
      - name: Build and install SVT-AV1
        run: sudo -E cmake --build Build --parallel 4 --target install
      - name: Configure Gstreamer plugin
        run: meson setup gstreamer-plugin/build gstreamer-plugin -Dprefix=/usr
      - name: Build Gstreamer plugin
        run: sudo -E ninja -C gstreamer-plugin/build install
      - name: Download videos
        run: |
          for url in raw.githubusercontent.com/OpenVisualCloud/SVT-AV1-Resources/master randomderp.com; do
            curl -LO https://$url/video.tar.gz && break
          done
          tar xf video.tar.gz
      - name: Run Gstreamer
        run: |
          gst-launch-1.0 -v filesrc location=akiyo_cif.y4m \
            ! y4mdec \
            ! svtav1enc \
            ! webmmux \
            ! filesink location=akiyo.mkv
